### PR TITLE
Revision of updates, added to_check.txt, updated .gitignore

### PR DESCRIPTION
**Pull request by FabioLolix**
please change "Aturix" to "Asturix" in changelog

added file to_check.txt
added .~lock.gldt.csv# to .gitignore

Revision of previous updates:

## Reverted to Active

Damn Small Linux
Forum is active
Last rel: 4.11rc2 2012.09.27
http://distro.ibiblio.org/damnsmall/

Aptosid
last rel 2012.12.1
forum still active

AV (new rel in 2016)

Descent|OS (new alpha rel in 2016-02)

Symphony (not so old)

StartOS (need further investigation, in chinese)

Matriux
last rel 3rc1 2013.09.27

## Definitly Dead / Diseppeared / Dead website

Danix
Kaella
ArtistiX
Poseidon
MoLinux
Venenux
Estrella Roja
Resulinux
Liquid Lemur
NepaLinux
PureOS
SalineOS
Snowlinux
Polippix
PUD
Sabily
Newtoos
Papug
Gentoox
Swift

#Dead with Statement
Aquamorph
Asturix
Tango Studio

## Changed stop date to last stable release + 2 years

Toorox (last rel 2013.01.01, no forum activity)

Monomaxos (5 years old)

AriOS (4 years old, no web activity)

SecUntu (4 years old, no activity since November 2012)

Tuquito
Last rel: 	2012.06.29
last blog news	2012.09.28
last tweet 	2013.04.25

Doudou
last rel 2.1 6 December 2013
last forum activity 2015
last daily build (2.1) 2015.09.28
http://www.doudoulinux.org/web/english/breve/coming-release-hyperborea-2-2.html
coming release never come, posted on 31 March 2015

GNUguitariNUX
last rel 2011-08-31
last post January 25, 2012

Inquisitor
last rel 3.1 beta2 2009-10-20

Epidemic
last rel: 4.1 beta1	2013-03-05
No downloads
from: http://www.epidemiclinux.org/download/
Because of the long time the project Epidemic GNU / Linux remained dormant, the versions currently available, including the development (4.1 Beta1), have become obsolete, which is why we recommend to all who wish to know the Epidemic GNU / Linux, or who are looking for a newer version, they look out for the next development version 4.1 Beta 2, which will be available soon.

## Blacklisted

srvRX live
one alpha release only 2012.03.10

### CODE REVIEW

**Comment by konimex** [comment]
What is .~lock.gldt.csv# again? Ever since I edit this file I've never
encountered it. :/

**Comment by FabioLolix** [comment]
It is a temporary file created by libreoffice during gldt.csv editing

**Comment by TimonW-Dev** [comment]
@FabioLolix Why was I mentioned here? I am a bit confused about the connection between my repository which is a fork of another repository which has nothing to do with this repository.

I also corrected the error with the lock file in commit [93df16b ](https://github.com/TimonW-Dev/os-family-tree/commit/93df16be5ddac0d4c6a56796738efbcfb4f0449d) 9 minutes later.
image

**Comment by FabioLolix** [comment]
Hi, I haven't mentioned you here, this was linked as reference

**Comment by TimonW-Dev** [comment]
Okey, thanks for the quick reply. Has this been referenced automatically? Do I need to do anything else here?

**Comment by FabioLolix** [comment]
> Do I need to do anything else here?

No

> Has this been referenced automatically?

Links inside github look that way :)

**Comment by TimonW-Dev** [comment]
Thanks, I guess I've learnt something new ;D

**Pull request merged**
